In [10]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
# Sample scalar and array inputs
scaler = 3.7
arr = np.array([100, 200, 300, 101, 321, 123])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)

sin: [-0.50636564 -0.8732973  -0.99975584  0.45202579  0.52910827 -0.45990349]
cos: [ 0.86231887  0.48718768 -0.02209662  0.89200487  0.84855433 -0.88796891]
tan: [-0.58721392 -1.79252748 45.24474207  0.5067526   0.62354083  0.51792747]
asin: [0.31679903 0.67263981 1.20707506 0.32007921 1.57079633 0.39323399]
acos: [1.2539973  0.89815652 0.36372127 1.25071712 0.         1.17756233]
atan: [1.56079666 1.56579637 1.56746301 1.56089566 1.56768107 1.56266642]


In [12]:
# Creating a 3x2 matrix
matrix = np.array([[7.7, 5.3], [3.5, 7.1], [9.2, 6.7]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[7.7 5.3]
 [3.5 7.1]
 [9.2 6.7]]

sin:
 [[ 0.98816823 -0.83226744]
 [-0.35078323  0.72896904]
 [ 0.22288991  0.40484992]]

cos:
 [[ 0.15337386  0.55437434]
 [-0.93645669  0.68454667]
 [-0.97484362  0.91438315]]

tan:
 [[ 6.44287247 -1.5012734 ]
 [ 0.37458564  1.06489313]
 [-0.22864171  0.44275742]]

asine:
 [[0.99169813 0.61393332]
 [0.39026638 0.88157138]
 [1.57079633 0.81578075]]

acosine:
 [[0.57909819 0.95686301]
 [1.18052994 0.68922495]
 [0.         0.75501558]]

atangent:
 [[1.44164904 1.38430943]
 [1.29249667 1.43087166]
 [1.46252574 1.42263631]]

exp:
 [[2208.34799189  200.33680997]
 [  33.11545196 1211.96707449]
 [9897.12905874  812.40582517]]

log (natural):
 [[2.04122033 1.66770682]
 [1.25276297 1.96009478]
 [2.21920348 1.90210753]]

abs:
 [[7.7 5.3]
 [3.5 7.1]
 [9.2 6.7]]

sqrt:
 [[2.77488739 2.30217289]
 [1.87082869 2.66458252]
 [3.03315018 2.58843582]]

rem (remainder when divided by 2):
 [[1.7 1.3]
 [1.5 1.1]
 [1.2 0.7]]

round:
 [[8. 5.]
 [4. 7.]
 [9. 7.]]

fl

In [13]:
# Creating a 2x3 matrix can have float values
vec = np.array([[99.9, 100.33, 33.1], [43.4, 53.3, 62.5]])

max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 100.33 at index 1
Min value: 33.1 at index 2
Length of vector: 2
Sorted vector: [[ 33.1   99.9  100.33]
 [ 43.4   53.3   62.5 ]]
Sum of elements: 392.53000000000003
Product of elements: 47964646728.48713
Median value: 57.9
Mean value: 65.42166666666667
Standard deviation: 26.11660417988696


In [14]:
# Creating a 2x3 matrix with float values
matrix_2x3 = np.array([[7.5, 2.2, 9.5], [8.1, 2.5, 4.3]])

# 1. Max & Min with indices
max_value = np.max(matrix_2x3)
max_index = np.unravel_index(np.argmax(matrix_2x3), matrix_2x3.shape)

min_value = np.min(matrix_2x3)
min_index = np.unravel_index(np.argmin(matrix_2x3), matrix_2x3.shape)

# 2. Length of matrix
matrix_length = matrix_2x3.size  # Total number of elements

# 3. Sorted versions
sorted_entire = np.sort(matrix_2x3, axis=None)[::-1]  # Entire matrix descending
sorted_rows = np.sort(matrix_2x3, axis=1)[:, ::-1]  # Row-wise descending

# 4. Sum and Product
sum_values = np.sum(matrix_2x3)
prod_values = np.prod(matrix_2x3)

# 5. Median, Mean, Standard Deviation
median_value = np.median(matrix_2x3)
mean_value = np.mean(matrix_2x3)
std_dev = np.std(matrix_2x3)

# Display results
print("Matrix:\n", matrix_2x3)
print("\nMax value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Matrix length (total elements):", matrix_length)
print("\nSorted entire matrix (descending):", sorted_entire)
print("\nSorted row-wise (descending):\n", sorted_rows)
print("\nSum of elements:", sum_values)
print("Product of elements:", prod_values)
print("\nMedian value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Matrix:
 [[7.5 2.2 9.5]
 [8.1 2.5 4.3]]

Max value: 9.5 at index (np.int64(0), np.int64(2))
Min value: 2.2 at index (np.int64(0), np.int64(1))
Matrix length (total elements): 6

Sorted entire matrix (descending): [9.5 8.1 7.5 4.3 2.5 2.2]

Sorted row-wise (descending):
 [[9.5 7.5 2.2]
 [8.1 4.3 2.5]]

Sum of elements: 34.099999999999994
Product of elements: 13649.006249999999

Median value: 5.9
Mean value: 5.683333333333333
Standard deviation: 2.825135198338106
